### ISSUE TITLE
Update current package

### ISSUE THREAD

**Issue by minhnguyen0712** [minhnguyen0712/SudokuRNApp#6]

**Comment by marlonemmerich** [comment]
Hey, friend! I created a [PR](https://github.com/minhnguyen0712/SudokuRNApp/pull/9)
Can you check please?
Now we have only node-fetch with problem:
![image](https://user-images.githubusercontent.com/52637919/97788471-f76c1780-1b97-11eb-8f76-8d21ad4004f1.png)
But the v3 is in beta  =/
If you want i can upgrade too
Cya!

**Comment by minhnguyen0712** [comment]
Thanks @marlonemmerich , just this is enough. I'm closing the issue.
